# Generated by Django 4.1.7 on 2023-04-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course_course_added_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
