# Generated by Django 4.1.7 on 2023-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
