# Generated by Django 4.1.7 on 2023-04-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_course_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_time',
        ),
    ]
