# Generated by Django 4.1.7 on 2023-04-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_course_course_time'),
        ('myapp', '0004_schedule_isrejected'),
    ]

    operations = [
    ]
