# Generated by Django 4.1.7 on 2023-04-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_courselist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseList',
        ),
    ]
