# Generated by Django 4.1.7 on 2023-04-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_courselist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseList',
        ),
    ]
