# Generated by Django 4.1.7 on 2023-04-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_courselist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseList',
        ),
    ]
