# Generated by Django 4.1.7 on 2023-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_courselist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
